name: CI
on:
  push:
    branches: [main, public-package]
  pull_request:
    branches: [main, public-package]

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Prerequisites
      run: sudo apt-get -y install autoconf automake libtool nasm zlib1g-dev libpng-dev libimagequant-dev
    - run: npm install
    - run: npm test
      env:
        CI: true

  macos:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Prerequisites
      run: |
        brew install cmake autoconf automake libtool nasm zlib libimagequant
        brew list --versions
        ln -s `brew --prefix libpng`/lib/libpng16.a /usr/local/lib/libpng16.a
        echo "ASM_NASM=\"`brew --prefix nasm`/bin/nasm\"" >> $GITHUB_ENV
        echo "VERBOSE=true" >> $GITHUB_ENV

    - name: Install Packages
      run: |
        echo "ASM_NASM=$ASM_NASM"
        echo "VERBOSE=$VERBOSE"
        echo "***"
        npm install --loglevel verbose --foreground-scripts

    - run: npm test
      env:
        CI: true

  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true
