name: CI
on:
  push:
    branches: [main, public-package]
  pull_request:
    branches: [main, public-package]

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Prerequisites
      run: sudo apt-get -y install autoconf automake libtool nasm zlib1g-dev libpng-dev libimagequant-dev
    - run: npm install
    - run: npm test
      env:
        CI: true

  macos:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Prerequisites
      run: |
        brew install cmake autoconf automake libtool nasm zlib libimagequant
        brew list --versions
        echo "LDFLAGS=\"-L`brew --prefix zlib`/lib\"" >> $GITHUB_ENV
        echo "CPPFLAGS=\"-I`brew --prefix zlib`/include\"" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=\"`brew --prefix zlib`/lib/pkgconfig\"" >> $GITHUB_ENV

    - name: Install Packages
      run: |
        echo "LDFLAGS=$LDFLAGS"
        echo "CPPFLAGS=$CPPFLAGS"
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
        npm install --loglevel verbose

    - run: npm test
      env:
        CI: true

  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true
